# Generated by Django 6.0.5 on 2026-05-20 07:14

import django.db.models.deletion
import store.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiamondSeries',
            fields=[
                ('id', models.CharField(default=store.models.generate_id, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rate_per_carat', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('diamond_type', models.CharField(choices=[('Both', 'Both'), ('Natural', 'Natural'), ('Lab', 'Lab')], default='Both', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('brand_margin', models.FloatField(blank=True, null=True)),
                ('certification_cost', models.FloatField(blank=True, null=True)),
                ('clarity', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('cut', models.CharField(blank=True, max_length=50, null=True)),
                ('setting_charges', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'diamond series',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.CharField(default=store.models.generate_id, max_length=50, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount')], max_length=20)),
                ('value', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('min_purchase', models.FloatField(default=0)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('usage_limit', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyValueStore',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.CharField(default=store.models.generate_id, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('items', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', models.CharField(default=store.models.generate_id, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('price_per_gram', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxClass',
            fields=[
                ('id', models.CharField(default=store.models.generate_id, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rate_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], default='percentage', max_length=20)),
                ('rate_value', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(default=store.models.generate_id, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='store.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=store.models.generate_id, max_length=50, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_email', models.CharField(blank=True, max_length=255)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('items', models.JSONField(default=list)),
                ('shipping_address', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('discount', models.JSONField(blank=True, default=dict, null=True)),
                ('shipping_carrier', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('subtotal', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=store.models.generate_id, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('gross_weight', models.FloatField(default=0)),
                ('net_weight', models.FloatField(default=0)),
                ('making_charge_type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], default='percentage', max_length=20)),
                ('making_charge_value', models.FloatField(default=0)),
                ('auto_price_enabled', models.BooleanField(default=True)),
                ('manual_price', models.FloatField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=500)),
                ('seo_description', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variants', models.JSONField(blank=True, default=list)),
                ('media', models.JSONField(blank=True, default=list)),
                ('certificates', models.JSONField(blank=True, default=list)),
                ('price_breakup', models.JSONField(blank=True, default=dict)),
                ('display_price', models.FloatField(blank=True, null=True)),
                ('availability', models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock'), ('made_to_order', 'Made to Order')], default='in_stock', max_length=30)),
                ('has_diamonds', models.BooleanField(default=False)),
                ('diamond_details', models.JSONField(blank=True, default=list)),
                ('cross_sell_products', models.JSONField(blank=True, default=list)),
                ('upsell_products', models.JSONField(blank=True, default=list)),
                ('height', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('feature_tabs', models.JSONField(blank=True, default=list)),
                ('gallery_images', models.JSONField(blank=True, default=list)),
                ('has_ring_size', models.BooleanField(default=False)),
                ('has_size_dimensions', models.BooleanField(default=False)),
                ('show_gallery_grid', models.BooleanField(default=False)),
                ('has_stones', models.BooleanField(default=False)),
                ('stone_details', models.JSONField(blank=True, default=list)),
                ('discount_percentage', models.FloatField(blank=True, null=True)),
                ('original_price', models.FloatField(blank=True, null=True)),
                ('discount_type', models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], max_length=20, null=True)),
                ('discount_value', models.FloatField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='store.category')),
                ('metal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.metal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.CharField(default=store.models.generate_id, max_length=50, primary_key=True, serialize=False)),
                ('reviewer_name', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Purity',
            fields=[
                ('id', models.CharField(default=store.models.generate_id, max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('fineness', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purities', to='store.metal')),
            ],
            options={
                'verbose_name_plural': 'purities',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='purity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.purity'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.taxclass'),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, to='store.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
