# Generated by Django 6.0.5 on 2026-05-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_add_product_seo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='making_charge_discount',
            field=models.FloatField(blank=True, help_text='Discount % applied to making charge and resulting tax', null=True),
        ),
    ]
